from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from calaccess_raw.models.base import CalAccessBaseModel


@python_2_unicode_compatible
class NetFileAgency(CalAccessBaseModel):
    """
    Netfile "Agencies" for reporting data.
    """
    agency_id = models.IntegerField(
        db_column='id',
        primary_key = True

    )
    shortcut_name = models.CharField(
        max_length=1024,
        db_column='shortcut'
    )
    name = models.CharField(
        max_length=1024,
        db_column='name'
    )

    class Meta:
        app_label = 'netfile'
        db_table = 'netfile_agency'
        verbose_name = 'NETFILE_AGENCY'
        verbose_name_plural = 'NETFILE_AGENCY'

    def __str__(self):
        return "%: %s" % (self.agency_id, self.name)


class NetFileCal201Transaction(CalAccessBaseModel):
    """
    Netfile 201 data.
    """
    agency_shortcut = models.CharField(
        max_length=32,
        db_column='agency_shortcut')
    filerId = models.CharField(
        max_length=32,
        db_column='filerId')
    dist_No = models.CharField(
        max_length=32,
        db_column='dist_No')
    end_Bal = models.FloatField(
        null=True,
        db_column='end_Bal')
    amountType = models.IntegerField(
        null=True,
        db_column='amountType')
    tran_Zip4 = models.CharField(
        max_length=10,
        db_column='tran_Zip4')
    tran_Id = models.CharField(
        max_length=32,
        db_column='tran_Id')
    loan_Date1 = models.DateField(
        null=True,
        db_column='loan_Date1')
    loan_Date2 = models.DateField(
        null=True,
        db_column='loan_Date2')
    tran_NamL = models.CharField(
        max_length=256,
        db_column='tran_NamL')
    tran_NamF = models.CharField(
        max_length=256,
        db_column='tran_NamF')
    tran_NamS = models.CharField(
        max_length=256,
        db_column='tran_NamS')
    tran_NamT = models.CharField(
        max_length=256,
        db_column='tran_NamT')
    tran_Dscr = models.CharField(
        max_length=256,
        db_column='tran_Dscr')
    intr_Emp = models.CharField(
        max_length=256,
        db_column='intr_Emp')
    tran_City = models.CharField(
        max_length=256,
        db_column='tran_City')
    tran_Amt1 = models.FloatField(
        null=True,
        db_column='tran_Amt1')
    g_From_E_F = models.CharField(
        max_length=1,
        db_column='g_From_E_F')
    cmte_Id = models.CharField(
        max_length=32,
        db_column='cmte_Id')
    loan_Amt8 = models.FloatField(
        null=True,
        db_column='loan_Amt8')
    amt_Incur = models.FloatField(
        null=True,
        db_column='amt_Incur')
    filingId = models.IntegerField(
        null=True,
        db_column='filingId')
    bakRef_TID = models.CharField(
        max_length=32,
        db_column='bakRef_TID')
    loan_Amt2 = models.FloatField(
        null=True,
        db_column='loan_Amt2')
    loan_Amt3 = models.FloatField(
        null=True,
        db_column='loan_Amt3')
    tres_Zip4 = models.CharField(
        max_length=10,
        db_column='tres_Zip4')
    loan_Amt6 = models.FloatField(
        null=True,
        db_column='loan_Amt6')
    loan_Amt7 = models.FloatField(
        null=True,
        db_column='loan_Amt7')
    loan_Amt4 = models.FloatField(
        null=True,
        db_column='loan_Amt4')
    loan_Amt5 = models.FloatField(
        null=True,
        db_column='loan_Amt5')
    sup_Opp_Cd = models.CharField(
        max_length=1,
        db_column='sup_Opp_Cd')
    memo_Code = models.CharField(
        max_length=1,
        db_column='memo_Code')
    intr_Adr2 = models.CharField(
        max_length=256,
        db_column='intr_Adr2')
    intr_NamT = models.CharField(
        max_length=256,
        db_column='intr_NamT')
    intr_NamS = models.CharField(
        max_length=256,
        db_column='intr_NamS')
    intr_NamL = models.CharField(
        max_length=256,
        db_column='intr_NamL')
    externalId = models.CharField(
        max_length=256,
        db_column='externalId')
    intr_NamF = models.CharField(
        max_length=256,
        db_column='intr_NamF')
    transactionType = models.IntegerField(
        null=True,
        db_column='transactionType')
    tres_NamL = models.CharField(
        max_length=256,
        db_column='tres_NamL')
    calculated_Amount = models.FloatField(
        null=True,
        db_column='calculated_Amount')
    tres_NamF = models.CharField(
        max_length=256,
        db_column='tres_NamF')
    intr_Self = models.CharField(
        max_length=256,
        db_column='intr_Self')
    tres_NamS = models.CharField(
        max_length=256,
        db_column='tres_NamS')
    tres_NamT = models.CharField(
        max_length=256,
        db_column='tres_NamT')
    tran_Emp = models.CharField(
        max_length=256,
        db_column='tran_Emp')
    tran_Adr2 = models.CharField(
        max_length=256,
        db_column='tran_Adr2')
    tres_ST = models.CharField(
        max_length=2,
        db_column='tres_ST')
    intr_ST = models.CharField(
        max_length=2,
        db_column='intr_ST')
    intr_Zip4 = models.CharField(
        max_length=10,
        db_column='intr_Zip4')
    intr_Adr1 = models.CharField(
        max_length=256,
        db_column='intr_Adr1')
    elec_Date = models.DateField(
        null=True,
        db_column='elec_Date')
    tran_Amt2 = models.FloatField(
        null=True,
        db_column='tran_Amt2')
    xref_SchNum = models.CharField(
        max_length=2,
        db_column='xref_SchNum')
    xref_Match = models.CharField(
        max_length=1,
        db_column='xref_Match')
    int_Rate = models.CharField(
        max_length=9,
        db_column='int_Rate')
    juris_Cd = models.CharField(
        max_length=3,
        db_column='juris_Cd')
    tran_Code = models.CharField(
        max_length=32,
        db_column='tran_Code')
    off_S_H_Cd = models.CharField(
        max_length=1,
        db_column='off_S_H_Cd')
    office_Cd = models.CharField(
        max_length=3,
        db_column='office_Cd')
    bal_Juris = models.CharField(
        max_length=256,
        db_column='bal_Juris')
    loan_Amt1 = models.FloatField(
        null=True,
        db_column='loan_Amt1')
    tran_ChkNo = models.CharField(
        max_length=256,
        db_column='tran_ChkNo')
    lender_Name = models.CharField(
        max_length=256,
        db_column='lender_Name')
    form_Type = models.CharField(
        max_length=32,
        db_column='form_Type')
    tran_Date = models.DateField(
        null=True,
        db_column='tran_Date')
    latitude = models.CharField(
        max_length=256,
        db_column='latitude')
    tran_Type = models.CharField(
        max_length=1,
        db_column='tran_Type')
    longitude = models.CharField(
        max_length=256,
        db_column='longitude')
    rec_Type = models.CharField(
        max_length=32,
        db_column='rec_Type')
    intr_City = models.CharField(
        max_length=256,
        db_column='intr_City')
    tran_Adr1 = models.CharField(
        max_length=256,
        db_column='tran_Adr1')
    int_CmteId = models.CharField(
        max_length=32,
        db_column='int_CmteId')
    calculated_Date = models.DateField(
        null=True,
        db_column='calculated_Date')
    bal_Name = models.CharField(
        max_length=1024,
        db_column='bal_Name')
    office_Dscr = models.CharField(
        max_length=256,
        db_column='office_Dscr')
    loan_Rate = models.FloatField(
        null=True,
        db_column='loan_Rate')
    filerName = models.CharField(
        max_length=256,
        db_column='filerName')
    beg_Bal = models.FloatField(
        null=True,
        db_column='beg_Bal')
    memo_RefNo = models.CharField(
        max_length=256,
        db_column='memo_RefNo')
    tran_Occ = models.CharField(
        max_length=256,
        db_column='tran_Occ')
    tran_Date1 = models.DateField(
        null=True,
        db_column='tran_Date1')
    amt_Paid = models.FloatField(
        null=True,
        db_column='amt_Paid')
    entity_Cd = models.CharField(
        max_length=3,
        db_column='entity_Cd')
    tres_Adr1 = models.CharField(
        max_length=256,
        db_column='tres_Adr1')
    tres_Adr2 = models.CharField(
        max_length=256,
        db_column='tres_Adr2')
    intr_Occ = models.CharField(
        max_length=256,
        db_column='intr_Occ')
    netFileKey = models.CharField(
        max_length=32,
        db_column='netFileKey')
    bal_Num = models.CharField(
        max_length=32,
        db_column='bal_Num')
    cand_NamF = models.CharField(
        max_length=256,
        db_column='cand_NamF')
    cand_NamL = models.CharField(
        max_length=256,
        db_column='cand_NamL')
    cand_NamS = models.CharField(
        max_length=256,
        db_column='cand_NamS')
    cand_NamT = models.CharField(
        max_length=256,
        db_column='cand_NamT')
    tres_City = models.CharField(
        max_length=256,
        db_column='tres_City')
    juris_Dscr = models.CharField(
        max_length=256,
        db_column='juris_Dscr')
    tran_Self = models.CharField(
        max_length=256,
        db_column='tran_Self')
    tran_ST = models.CharField(
        max_length=2,
        db_column='tran_ST')

    class Meta:
        app_label = 'netfile'
        db_table = 'netfile_cal201_transaction'
        verbose_name = 'NETFILE_CAL201_TRANSACTION'
        verbose_name_plural = 'NETFILE_CAL201_TRANSACTION'
