#!/bin/bash
set -exuo pipefail

now=$(date +%s)
deploy_dir=/data/backend/$now

echo 'Fetching latest commits from https://github.com/opencalifornia/disclosure-backend.git...'
cd /data/git/disclosure-backend && git fetch

echo "Deploying into ${deploy_dir}..."
sudo -u backend /bin/bash -c "
  mkdir -p $deploy_dir &&
  git archive HEAD | tar xC $deploy_dir &&
  source /data/backend/env/bin/activate &&
  pip install -r $deploy_dir/requirements_dev.txt &&
  pip install uwsgi &&
  ln -sfT $deploy_dir /data/backend/current
"

echo "Done!"
